export class IntructionSpecial{
    id:number;
    instructionID:number;
    instructionName:string;
    expertName:string;
    referrerDescription:string;
    specialityName:string;
    incidentType:string;
    clientRefNo:string;
    medicoRefNo:string;
    expertID:number;
    referrerID:number;
    specialityID:number;
    incidentTypeID:number;
    specialNote:string;
    isSpecialRestrictionNeed:boolean;
    specialRestrictionNeed:string;
    instructionState:string;
    isApproved:boolean;
    state:string;
    stateID:number;
    userID:number;
}