export class OutstandingAppointments{
    id:string;
    firstName:string;
    lastName:string;
    gender:string;
    instructionCode:string;
    dob:string;
    mobileNumber:string;
    email:string;
    clientRefNo:string;
    medicoRefNo:string;
    expertID:number;
    referrerID:number;
    incidentTypeID:number;
    specialNote:string;
    isSpecialRestrictionNeed:boolean;
    userID:number;
    specialRestrictionNeed:string;
}