export class MedicalSecretary{
  id:number;
  namePrefix: string;
  lastName: string;
  firstName: string;
  middleName: string;
  nameSuffix: string;
  fullName: string;
  gender: string;
  addressLine1: string;
  addressLine2: string;
  county: string;
  town: string;
  postCode: string;
  phoneNo: string;
  email: string;
  mobileNumber: string;
  medicalSecretaryContractType: string;
  amountRate: string;
  medicalSecretaryTypeID:number=1;
  status: string;
  isActive: boolean;
  createdByID: number;
  lastModifiedBy: number;
  companyName: string;
  companyAddress: string;
  companyPhoneNumber: string;
  reportWritingCount: 0;
  additionalEmailJson: string;
  isDirectMedSecretary: boolean;
  isLinkMedSec: boolean;
  isHourlyFee: boolean;
  isPerRptFee: boolean;
  fees: string;
  isHourlyOrPerReportFee:string;
  isUser:boolean;
  username:string;
  password:string;
  confrimPassword:string;
  userID:number;
}