export class Referrer{
    id:number;
    description:string;
    addressLine1:string;
    addressLine2:string;
    referrerCode:string;
    country:string;
    town:string;
    postCode:string;
    phoneNo:string;
    alternatePhoneNo:string;
    faxNo:string;
    email:string;
    rptDueDays:string;
    enableSMS:string;
    enableEmail:string;
    enableQuickInstruction:string;
    logoPath:string;
    companyNo:string;
    referrerType:number;
    expertType:number;
    sessionDueDays:number;
    sessionOutOfDueDays:number;
    approxDueDaysDischarge:number;
    userID:number;
    referrerCodeOut:string;
}